version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongo-users:
    image: mongo
    container_name: mongo-users
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users

  mongo-orders:
    image: mongo
    container_name: mongo-orders
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: orders

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo-users
      - kafka

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo-orders
      - kafka
